### ISSUE TITLE
Conversation 

### ISSUE THREAD

**Issue by efortney** [efortney/CSC406-Banking#1]
How would you guys prefer to communicate for this project? 

Leave a comment if you have a preferred method.

**Comment by w3ifor** [comment]
I prefer meeting

**Comment by jguinn2** [comment]
No preference from me, anything works

**Comment by efortney** [comment]
@jguinn2 i sent you a link to be a collaborator. i think you have to accept that in order for me to give you rights to this repo.

**Comment by efortney** [comment]
I created a group me for this project and I believe that I sent the link to it for you guys. It will be easier for us to set up meetings through that. If you didnt get an invite, here is the link to it. 
https://groupme.com/join_group/44909957/sFgmtA

**Comment by w3ifor** [comment]
[case study-software requirement.pdf](https://github.com/efortney/CSC406-Banking/files/2457800/case.study-software.requirement.pdf)

**Comment by w3ifor** [comment]
I found something might be useful

**Comment by efortney** [comment]
@w3ifor definitely something we can use. Can you open a PR and add it to the links section in the README?
