### ISSUE TITLE
FE-01 Setup Java FX 

### ISSUE THREAD

**Issue by efortney** [efortney/CSC406-Banking#18]
We need to create a basic FX screen in order to have something up and running. 
The first implementation of this needs to be a branch off of main. 

User Story: 
As a user, I want to be able to view my banking application through an interface, so that I don't have to go into the bank. 

I'll know I'm done when:
- [x] Running the java main line starts a Java FX screen

**Comment by NLuu1023** [comment]
We have talked about the customer interface page designs.  Currently have a tentative opening page.

**Comment by efortney** [comment]
@NLuu1023 sweet, I'm just adding these so we can keep track of what we have done and what we need to do.
